FROM node:16-alpine as main

ARG APP_USER=docker
ARG APP_GROUP=docker
ARG APP_USER_ID=1000
ARG APP_GROUP_ID=1000

# Add user
RUN deluser --remove-home node \
    && addgroup -g ${APP_GROUP_ID} ${APP_GROUP} \
    && adduser -u ${APP_USER_ID} -G ${APP_GROUP} -h /home/${APP_USER} -D ${APP_USER} \
;

ARG APP_CODE_PATH="/var/www/html"
WORKDIR "${APP_CODE_PATH}"

FROM main as dev

CMD ["yarn", "run", "watch"]