version: '3.3'
services:
  fpm:
    build: .
    restart: always
    volumes:
      - ".:/app"
      - "html:/var/www/html"
    networks:
      - mynet

  nginx:
    image: nginx
    ports:
      - 9580:80
      - 443:443
    restart: always
    links:
      - fpm
      - db
    volumes:
      - ".:/app"
      - "html:/var/www/html"
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mynet

  #MySQL Service
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassworddb
      MYSQL_ROOT_PASSWORD: rootpasswordmysql
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - mynet


networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local
  html: